#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=ring;size=3;add_cosmetic=true", "id=charm;size=1;add_cosmetic=true", "id=belt;size=3;add_cosmetic=true"]

