on:
  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: build and deploy
      run: |
        dir > test.txt
        ./build.bat
        # Note: the following account information will not work on GHES
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "generated"
        git push
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/ScorchOriginPackThingy-1.0.0.zip
        asset_name: export.zip
        tag: Release
        overwrite: true
        body: "This is my release text"
